repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.23.1
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        alias: autoformat
        additional_dependencies:
          - black==22.12.0

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]

  # currently errors with the entry-points:
  # [ERROR] `project.entry-points` keys must be named by:
  #   {format: 'python-entrypoint-group'}
  # but how it's setup in this project's `pyproject.toml` is how the docs say it should be setup:
  # https://setuptools.pypa.io/en/latest/userguide/entry_point.html#entry-points-for-plugins
  # - repo: https://github.com/abravalheri/validate-pyproject
  #   rev: v0.23
  #   hooks:
  #     - id: validate-pyproject
  #       additional_dependencies: ["validate-pyproject-schema-store[all]"]
